[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["crawler"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://www.seosnafu.co.uk/*"
  to = "https://seosnafu.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.seosnafu.co.uk/*"
  to = "https://seosnafu.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://seosnafu.co.uk/*"
  to = "https://seosnafu.co.uk/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Robots-Tag = "all"